# Generated by Django 2.2.13 on 2020-08-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_affiliate_discount_used',
            new_name='is_referral_code_used',
        ),
    ]
