# Generated by Django 2.2.13 on 2020-08-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_referrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bonuses',
        ),
    ]
