# Generated by Django 2.1.11 on 2019-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_affiliate_discount_used',
            field=models.BooleanField(default=False),
        ),
    ]
