# Generated by Django 2.1.11 on 2019-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_affiliate_discount_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonuses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
