# Generated by Django 2.2.13 on 2020-08-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_squashed_0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='date_of_birth',
        ),
    ]
