# Generated by Django 2.2.13 on 2020-08-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_create_birthday_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayCondition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
    ]
