# Generated by Django 2.2.13 on 2020-08-25 10:29

import apps.offer.conditions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_create_referral_code_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCodeCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.Condition')),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
                'abstract': False,
            },
            bases=(apps.offer.conditions.CustomConditionMixin, 'offer.condition'),
        ),
    ]
