# Generated by Django 2.2.13 on 2020-08-25 13:08

from django.db import migrations

from oscar.apps.offer.custom import create_condition


def create_referrer_condition(apps, schema_editor):
    from apps.offer.conditions import ReferrerCondition

    create_condition(ReferrerCondition)


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_referralcodecondition'),
    ]

    operations = [
        migrations.RunPython(create_referrer_condition)
    ]
